[http.middlewares.middlewares-rate-limit]
  [http.middlewares.middlewares-rate-limit.rateLimit]
    average = 100
    burst = 50

[http.middlewares.middlewares-secure-headers]
  [http.middlewares.middlewares-secure-headers.headers]
    accessControlAllowMethods= ["GET", "OPTIONS", "PUT"]
    accessControlMaxAge = 100
    hostsProxyHeaders = ["X-Forwarded-Host"]
    sslRedirect = true
    stsSeconds = 63072000
    stsIncludeSubdomains = true
    stsPreload = true
    forceSTSHeader = true
    customFrameOptionsValue = "allow-from https:example.com" #CSP takes care of this but may be needed for organizr. 
    contentTypeNosniff = true 
    browserXssFilter = true 
    referrerPolicy = "same-origin" 
    featurePolicy = "camera 'none'; geolocation 'none'; microphone 'none'; payment 'none'; usb 'none'; vr 'none';" 
    [http.middlewares.middlewares-secure-headers.headers.customResponseHeaders]
      X-Robots-Tag = "none,noarchive,nosnippet,notranslate,noimageindex,"
      server = ""

[http.middlewares.middlewares-oauth]
  [http.middlewares.middlewares-oauth.forwardAuth]
    address = "http://oauth:4181"
    trustForwardHeader = true
    authResponseHeader = ["X-Forwarded-User"]

